export const apiPaths = {
  auth: "/auth",
  login: "/auth/login",
  register: "/auth/register",
  me: "/auth/me",
  products: "/products",
  productsAdminAll: "/products/admin/all",
  productDetail: (productId: string) => `/products/${productId}`,
  cart: "/cart",
  cartItems: "/cart/items",
  orders: "/orders",
  ordersCheckout: "/orders/checkout",
  ordersFromQuote: "/orders/from-quote",
  ordersAdminAll: "/orders/admin/all",
  orderPayDemo: (orderId: string) => `/orders/${orderId}/pay-demo`,
  orderCancel: (orderId: string) => `/orders/${orderId}/cancel`,
  orderStatus: (orderId: string) => `/orders/${orderId}/status`,
  chatSessions: "/chat/sessions",
  chatSessionClaim: (sessionId: string) => `/chat/sessions/${sessionId}/claim`,
  chatSessionRelease: (sessionId: string) =>
    `/chat/sessions/${sessionId}/release`,
  chatTranslatePreview: (sessionId: string) =>
    `/chat/sessions/${sessionId}/translate-preview`,
  chatSessionQuote: (sessionId: string) => `/chat/sessions/${sessionId}/quotes`,
  advisorAsk: "/advisor/ask",
  craftsmanAsk: "/webhooks/craftsman/ask",
  uploadImage: "/uploads/image",
  pushVapidPublicKey: "/push/vapid-public-key",
  pushSubscribe: "/push/subscribe",
} as const
