export const apiPaths = {
  auth: "/auth",
  login: "/auth/login",
  register: "/auth/register",
  me: "/auth/me",
  products: "/products",
  productsAdminAll: "/products/admin/all",
  cart: "/cart",
  cartItems: "/cart/items",
  orders: "/orders",
  ordersCheckout: "/orders/checkout",
  orderPayDemo: (orderId: string) => `/orders/${orderId}/pay-demo`,
  orderCancel: (orderId: string) => `/orders/${orderId}/cancel`,
  chatSessions: "/chat/sessions",
  chatTranslatePreview: (sessionId: string) =>
    `/chat/sessions/${sessionId}/translate-preview`,
  advisorAsk: "/advisor/ask",
  craftsmanAsk: "/webhooks/craftsman/ask",
  uploadImage: "/uploads/image",
  pushVapidPublicKey: "/push/vapid-public-key",
  pushSubscribe: "/push/subscribe",
} as const
